### ISSUE TITLE
Current status?

### ISSUE THREAD

**Issue by micahwedemeyer** [danschultzer/ex_oauth2_provider#2]
I'm looking to add an OAuth provider component to a Phoenix app I'm on, and this library looks like one of the more promising ones. What's the current status? Semi-functional? Production-ready?

In my case, it doesn't need to be bulletproof, and I'm happy to help out and contribute back. I'm just wondering if it's anywhere near functional at this point.

Thanks!

**Comment by danschultzer** [comment]
I expect to have it fully working in a couple of weeks. There'll be another library going up soon that will take care of routes, controllers, and views in Phoenix. This library will do the heavy lifting with plug/schema/authorization.

Right now there's just the access token handling. I'm working on request handling which should make this library functional. When that's up I would love to have some help fleshing it more out.

I've got a project that depends on this, so working every day on it.

**Comment by micahwedemeyer** [comment]
Looks like it already fulfills my needs. I was able to generate a token and associate it to a User and an Oauth app. If I run into anything I need that's not there, I'll make sure to send a pull request.

Thanks!

**Comment by danschultzer** [comment]
Great, I got request handling working now so any PR would be much appreciated.

**Comment by danschultzer** [comment]
Hey @micahwedemeyer, just letting you know that v0.1.0 has been released on [hex.pm](https://hex.pm/packages/ex_oauth2_provider). Also there's [phoenix_oauth2_provider](https://hex.pm/packages/phoenix_oauth2_provider) for fast integration with Phoenix.
