### ISSUE TITLE
Unable to compile using Schema for UUID

### ISSUE THREAD

**Issue by erikreedstrom** [danschultzer/ex_oauth2_provider#23]
I have set up configuration in accordance with the instructions for UUID, but this causes the app to fail compilation on a clean build. The schema module is compiled after the dependency, but since the dependency requires the schema for expansion, it fails during compile.

`lib/ex_oauth2_provider/oauth_access_grants/oauth_access_grant.ex:4: ExOauth2Provider.OauthAccessGrants.OauthAccessGrant (module)
    expanding macro: ExOauth2Provider.Schema.__using__/1`

If one compiles without the configuration first, then adds the configuration and recompiles, it will work since the beam file is present then. However, this won't work for situations where builds need to occur from a clean state, such as new checkout or CI.

This also seems to be an issue with `resource_owner`. It fails to find the undefined module on compile here `lib/ex_oauth2_provider/utils.ex:34: ExOauth2Provider.Utils.schema_belongs_to_opts/1`.

**Comment by danschultzer** [comment]
Ugh, yeah, I should've tested with this library as a dependency. Thanks for letting me know @erikreedstrom, I'm testing out with a sample app and will work on a solution.

**Comment by danschultzer** [comment]
I've a solution in https://github.com/danschultzer/ex_oauth2_provider/pull/24 with [an updated readme](https://github.com/danschultzer/ex_oauth2_provider/blob/ca144ec911cef696aa49bf21410edac195571101/README.md#using-uuid-or-custom-primary-key-type)

I'm working out some kinks in https://github.com/danschultzer/phoenix_oauth2_provider/pull/9 and will then confirm with my sample app that everything works as expected, and the system can compile by default.

**Comment by danschultzer** [comment]
Works in my sample app :tada: `v0.3.0` has been released, let me know if it solves the issue.

**Comment by danschultzer** [comment]
Also, in case you're using `phoenix_oauth2_provider`, that library has been updated to `v0.3.2`.

**Comment by erikreedstrom** [comment]
Yep. All good now. Thanks!
