### ISSUE TITLE
`create_application/2` cannot be called with empty string for `secret`

### ISSUE THREAD

**Issue by erikreedstrom** [danschultzer/ex_oauth2_provider#28]
Although #27 was introduced, secret is being converted to `nil` by the cast in `new_application_changeset/3`.

IIRC, this value should either default to `""` in the schema, or have `:empty_values` added to the change prior to the cast, to prevent this behavior.

**Comment by danschultzer** [comment]
Thanks @erikreedstrom. My bad for not testing actual creation of an app with empty string secret. It has been fixed with `v0.3.2`.
