### ISSUE TITLE
Support more options of belongs_to association on OauthApplication

### ISSUE THREAD

**Issue by fahchen** [danschultzer/ex_oauth2_provider#38]
Now I have a schema named `User` which primary_key is `uuid` (**not `id`**), and I set it as `application_owner`.
When I `create_application` for a user, I got errors for I can't change `references` option of `belongs_to` (https://github.com/danschultzer/ex_oauth2_provider/blob/v0.4.1/lib/ex_oauth2_provider/oauth_applications/oauth_application.ex#L18). The same error happened at `ExOauth2Provider.OauthAccessTokens.OauthAccessToken` and `ExOauth2Provider.OauthAccessGrants.OauthAccessGrant`

```elixir
# This works
defmodule ExOauth2Provider.OauthApplications.OauthApplication do
  # ...
  schema "oauth_applications" do
    belongs_to :owner, Config.application_owner_struct(:module), type: Config.application_owner_struct(:foreign_key_type), references: :uuid
    # ...
  end
end
```
I check ecto code, I found the `related_key` is always to `:id` instead of `primary_key` of current schema. https://github.com/elixir-ecto/ecto/commit/43b564fae9c7bf0e1b5e12cd23a61c144c59395c
Can we support more options by codes like below:
```elixir
config :ex_oauth2_provider, ExOauth2Provider,
  application_owner: {Dummy.User, [type: :binary_id, references: :uuid]},

defmodule ExOauth2Provider.OauthApplications.OauthApplication do
  # ...
  schema "oauth_applications" do
    belongs_to :owner, Config.application_owner_struct(:module), Config.application_owner_struct(:options)
    # ...
  end
end
```

**Comment by danschultzer** [comment]
Yeah, that makes sense. I'll create a PR tomorrow to permit options to be used.

**Comment by fahchen** [comment]
I almost finish this today, I will create a PR later.

**Comment by danschultzer** [comment]
Thanks! 🙌

**Comment by danschultzer** [comment]
`v0.4.2` is out 🚀
