### ISSUE TITLE
Rewrite how ecto schema works

### ISSUE THREAD

**Issue by danschultzer** [danschultzer/ex_oauth2_provider#47]
## Changesets in schema module files

Right now changesets are in context file. This is incorrect behaviour.

## Generate schema module files when running install script

Schema module files should be generated in similar fashion to [Pow](https://github.com/danschultzer/pow)

There are too many issues with configuration during compile time (e.g. #46), and it's more appropriate to have the configuration handled by the developer in their app with the modules. It'll also handle UUID much better.

**Comment by blatyo** [comment]
Is this primary blocker for a new version of this library?

**Comment by danschultzer** [comment]
Yeah. I haven’t had enough time to pull this through yet, but it will be very similar to https://github.com/danschultzer/pow

**Comment by blatyo** [comment]
Specifically, like this? https://github.com/danschultzer/pow/blob/master/lib/mix/tasks/ecto/pow.ecto.gen.schema.ex#L1

**Comment by danschultzer** [comment]
Yeah, just with several schema modules instead of only one.

**Comment by danschultzer** [comment]
So I finally finished up the huge rewrite. Hopefully a release will be out within a week or two.

**Comment by blatyo** [comment]
Awesome! I had started to tackle this myself, but realized it was a lot larger scope than I realized. Was going to share the PR in case it was useful as a starting point, but noticed you had already changed this when I was about to create it.

https://github.com/danschultzer/ex_oauth2_provider/compare/master...blatyo:master?expand=1

**Comment by danschultzer** [comment]
Yeah the scope was extreme, but with this done, the repo should be much easier to work with moving forward 😄 You are more than welcome to help iron out anything in the repo.
