### ISSUE TITLE
Resource Owner 

### ISSUE THREAD

**Issue by elpic** [danschultzer/ex_oauth2_provider#48]
I'm using the grant type client_credentials and a pipeline with `ExOauth2Provider.Plug.VerifyHeader` and `ExOauth2Provider.Plug.EnsureAuthenticated` but every time I tried to obtain the resource_owner I get a null value

**Comment by danschultzer** [comment]
Can you show me the config? Sounds like it's missing the `:resource_owner` setting:

```elixir
config :ex_oauth2_provider, ExOauth2Provider,
  resource_owner: Dummy.Users.User
```

**Comment by elpic** [comment]
```
config :ex_oauth2_provider, ExOauth2Provider,
  repo: Elixir.Drogo.Repo,
  resource_owner: MyApp.Users.User```

**Comment by elpic** [comment]
Nevermind, I will try to update the `resource_owner` thanks and sorry

**Comment by elpic** [comment]
I update the config and I having the same issue as before :(

**Comment by danschultzer** [comment]
How do you fetch the resource owner? With `ExOauth2Provider.Plug.current_resource_owner(conn)`?

**Comment by danschultzer** [comment]
Sorry, I didn't read the issue correctly. There's no resource owner for client credential access tokens since it's application wide. Depending how your app works you would either use the application from the access token, or the owner for the application.
