### ISSUE TITLE
how to change access_token_expires_in time

### ISSUE THREAD

**Issue by upender-gleecus** [danschultzer/ex_oauth2_provider#49]
Hi I want to change the default **expires_in** for access_token now its: 7200.
I tried with below configuration but not working.
Can you please help me to fix this.
```
config :phoenix_oauth2_provider, PhoenixOauth2Provider,
  module: Myapp,
  repo: Myapp.Repo,
  grant_flows: ~w(client_credentials),
  resource_owner: Myapp.Coherence.User,  
  access_token_expires_in: 14400
```

**Comment by upender-gleecus** [comment]
It's working fine. actually its my mistake I didn't restarted server after changing configuration and tested in postman.

**Comment by danschultzer** [comment]
Oh thanks! Sorry I didn't get back to this sooner, but I had difficulty figuring out what went wrong and got distracted.
