### ISSUE TITLE
Do *not* use anonymous function instead of tuple for `:access_token_generator`, `:password_auth`, etc

### ISSUE THREAD

**Issue by OvermindDL1** [danschultzer/ex_oauth2_provider#65]
Anonymous functions should absolutely never ever appear in a config file.  Configuration files are loaded dynamically at code loading time, however when a release is made it gets lowered to Configuration AST and thus causes an error at release generation time due to invalid config file format.  Only MFA should be used in config files, absolutely never ever should an anonymous function or closure be allowed in the config file unless it is used **only** at code generation time and otherwise does not get generated for releases (which would require a release configuration that does not include it).

**Comment by danschultzer** [comment]
Ugh, thanks for letting me know! I didn't think #63 through, I'll add a PR asap to resolve this.
