### ISSUE TITLE
function Mix.env/0 is undefined

### ISSUE THREAD

**Issue by chasers** [danschultzer/ex_oauth2_provider#68]
Hey Dan!  Getting this on prod with my new production setup (dockerized with Elixir releases).  Any ideas?  I've tried putting `force_ssl_in_redirect_uri: true` just about everywhere in the config.

Latest stuff is on this branch: https://github.com/Logflare/logflare/tree/master-instance-group

I'm using it via your `phoenix_oauth2_provider` package.

Thanks again!

#PID<0.5575.7> running LogflareWeb.Endpoint (connection #PID<0.22745.5>, stream id 79) terminated Server: logflare.app:80 (http) Request: GET /oauth/authorize?scope=read%20write&response_type=code&redirect_uri=https%3A%2F%2Fwww.cloudflare.com%2Fapps%2Foauth%2F&client_id=d8a8af24ada66bfa29477d746d74ae7a8833d80019c6fa285f07fe6159491a5f&user.email=chase%40logflare.app&site.name=70waggy.com ** (exit) an exception was raised: ** (UndefinedFunctionError) function Mix.env/0 is undefined (module Mix is not available) Mix.env() (ex_oauth2_provider) lib/ex_oauth2_provider/config.ex:120: ExOauth2Provider.Config.force_ssl_in_redirect_uri?/1 (ex_oauth2_provider) lib/ex_oauth2_provider/redirect_uri.ex:40: ExOauth2Provider.RedirectURI.invalid_ssl_uri?/2 (ex_oauth2_provider) lib/ex_oauth2_provider/redirect_uri.ex:32: ExOauth2Provider.RedirectURI.do_validate/3 (ex_oauth2_provider) lib/ex_oauth2_provider/redirect_uri.ex:68: ExOauth2Provider.RedirectURI.valid_for_authorization?/3 (ex_oauth2_provider) lib/ex_oauth2_provider/oauth2/authorization/strategy/code.ex:220: ExOauth2Provider.Authorization.Code.validate_redirect_uri/2 (ex_oauth2_provider) lib/ex_oauth2_provider/oauth2/authorization/strategy/code.ex:189: ExOauth2Provider.Authorization.Code.validate_request/2 (ex_oauth2_provider) lib/ex_oauth2_provider/oauth2/authorization/strategy/code.ex:92: ExOauth2Provider.Authorization.Code.preauthorize/3

**Comment by danschultzer** [comment]
Fixed in #69, it's because `Mix.env` shouldn't be called on runtime. Weird this wasn't catched earlier.

**Comment by danschultzer** [comment]
Merged to master, can you test it out with the master branch?

```elixir
{:ex_oauth2_provider, github: "danschultzer/ex_oauth2_provider"}
```

**Comment by chasers** [comment]
Rad thanks! Yep can probably do this today, for sure tomorrow!

**Comment by chasers** [comment]
This works! Thanks again!

**Comment by danschultzer** [comment]
`v0.5.5` released
