### ISSUE TITLE
client_secret required

### ISSUE THREAD

**Issue by toyah** [danschultzer/ex_oauth2_provider#72]
I am using a SPA application, normally the client_secret should not be required when exchanging a code against a token. How will I proceed?

**Comment by danschultzer** [comment]
You should not set a secret for the application, and it will work per the readme: https://github.com/danschultzer/ex_oauth2_provider#authorization-code-flow-in-a-single-page-application

**Comment by toyah** [comment]
I see this but how to not set the secret ? when I create an application it's required (not nil and not blank). Thank you for your response :) 
For now I delete the secret directly in the database (and it run) but I think it's not the right procedure

**Comment by danschultzer** [comment]
Just setting the secret as an empty string should work. It can't be `nil` but it can be `""`.

**Comment by toyah** [comment]
I tested, It run with ""
But I must edit the template view generated with phoenix_oauth2_provider to add the secret field :)
Thank you very mutch.
