### ISSUE TITLE
Upgrade issue for ecto_sql to 3.9.2

### ISSUE THREAD

**Issue by eoh1980** [danschultzer/ex_oauth2_provider#99]
Upgrading our current `ecto_sql`  to `3.9.2` with the current `ex_oauth2_provider` `0.5.6` results in compile errors due to `ecto_sql` now disallowing schema fields with `null: false`.  But the `ex_oauth2_provider` `mix.exs` allows `ecto_sql ~> 3.0.0` https://github.com/danschultzer/ex_oauth2_provider/blob/master/mix.exs#L45 

Any calls to the function `access_grant_fields()` results in attempting to create the fields:
```
      {:token, :string, null: false},
      {:expires_in, :integer, null: false},
      {:redirect_uri, :string, null: false},
```
https://github.com/danschultzer/ex_oauth2_provider/blob/master/lib/ex_oauth2_provider/access_grants/access_grant.ex#L25-L31

Compile error with ecto_sql 3.9.2:
```
== Compilation error in file lib/engine/oauth_access_grants/oauth_access_grant.ex ==
** (ArgumentError) invalid option :null for field/3
    (ecto 3.9.4) lib/ecto/schema.ex:2227: Ecto.Schema.check_options!/3
    (ecto 3.9.4) lib/ecto/schema.ex:1926: Ecto.Schema.__field__/4
    (elixir 1.14.2) lib/enum.ex:975: Enum."-each/2-lists^foreach/1-0-"/2
    lib/engine/oauth_access_grants/oauth_access_grant.ex:14: (module)
```

**Comment by danschultzer** [comment]
This has been resolved with #100. v0.5.7 release will be out later today!
